### ISSUE TITLE
Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by lyus01306** [SchoolOfCode/bc17-w4d2-project-drop-and-give-me-twenty#3]
User Story: Implement functionality to GET all activities for a particular user

Description:

As Kenny, a busy front end engineer I need to be able to send a GET request with a user_id to the API to get a users activities so that I can make a nice simple dashboard that shows a user all of their activities.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a GET request to “http://localhost:3000/activities”

Then the the request should succeed, responding with the correct status code and an array of User Activity objects in the response body (response.data).
```[tasklist]
### Tasks
- [x] Create a JSON file to store User data
- [x] Create an array of activities
- [x] Put in dummy activity data
- [x] import JSON data into index.js
- [x] Create a gethandler for all activities
- [x] create a gethandler to get a specific activity
- [x] Request should send the correct status code
- [x] Research Rules/conventions for RESTapis
```
